### ISSUE TITLE
Cannot run

### ISSUE THREAD

**Issue by Shidooo** [recur74/valstats#1]
Does this project still work ? I got this problem

```
  File "C:\Users\Julien\Downloads\v.py", line 64
    'username': f'{username}',
                            ^
SyntaxError: invalid syntax
```

**Comment by recur74** [comment]
Hi. The f-strings are new in python since 3.6. Please check what version of python you are using with: 

`python -v`

If you have a python older than 3.6 i recommend to upgrade, but you can also change the two lines that use that syntax to:

            'username': '{}'.format(username),
            'password': '{}'.format(password),

Regards,
Anders
